//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIExpenseon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string RES_HOTEL { get; set; }
        public byte ESTRELAS { get; set; }
        public string LOGRADOURO { get; set; }
        public int NUMERO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public bool ESTACIONAMENTO { get; set; }
        public bool PISCINA { get; set; }
        public bool SAUNA { get; set; }
        public bool WIFI { get; set; }
        public bool RESTAURANTE { get; set; }
        public bool BAR { get; set; }
        public bool ACADEMIA { get; set; }
    }
}
